### PR TITLE
Files

### PR DESCRIPTION
**Pull request by mendozatudares**
If using eye tracking, gaze data gets written to a gaze#.csv file, which is then sent to the multicraft server's file transfer service on port 5004 upon closing the client

Tobii executable program has also been updated.

### CODE REVIEW

**Review by mitchellzhen — APPROVED** [review]
Looks good, though do we want to include the packaged ClientGUI outside of releases?

**Comment by mendozatudares** [comment]
> 
> 
> Looks good, though do we want to include the packaged ClientGUI outside of releases?

The packaged ClientGUI shouldn't be included in the source code

**Comment by mitchellzhen** [comment]
> > Looks good, though do we want to include the packaged ClientGUI outside of releases?
> 
> The packaged ClientGUI shouldn't be included in the source code

My bad, thought it was being added since it was removed from the gitignore.

**Comment by mendozatudares** [comment]
> 
> 
> > > Looks good, though do we want to include the packaged ClientGUI outside of releases?
> > 
> > 
> > The packaged ClientGUI shouldn't be included in the source code
> 
> My bad, thought it was being added since it was removed from the gitignore.

Oh my apologies, that should be handled already since the `dist` subdirectory is in the gitignore

**Pull request merged**
